### ISSUE TITLE
İ need help for minecarft modpack , MythicBotany and LibX is crashing i think

### ISSUE THREAD

**Issue by Apocalyptica20** [ModdingX/LibX#10]
[crash-2021-05-22_19.19.54-fml.txt](https://github.com/noeppi-noeppi/LibX/files/6526814/crash-2021-05-22_19.19.54-fml.txt)

**Comment by landretk** [comment]
We narrowed it down to a bug in minecraft getting the resource location for INTEGER with a Turkish dotless i due to the PC language being set to Turkish. Not sure if that's something that can be fixed in the mod or is something in minecraft itself. The Java function toLowerCase() uses locale, so somewhere its converting a string of "INTEGER" incorrectly.

He can load the game fine without MythicBotany installed, so maybe it can be fixed in the mod.

```
Mod File: MythicBotany-1.16.4-1.3.10.jar
	Failure message: MythicBotany (mythicbotany) has failed to load correctly
		java.lang.RuntimeException: Generated code threw an exception
	Mod Version: 1.16.4-1.3.10
	Mod Issue URL: http://placeholder.invalid
	Exception message: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:ınteger
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:42) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at io.github.noeppi_noeppi.libx.config.ConfigManager.lambda$static$0(ConfigManager.java:154) ~[libx:1.16.3-1.0.64] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.stream.IntPipeline$4$1.accept(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_291] {}
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:65) ~[guava-21.0.jar:?] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_291] {}
	at io.github.noeppi_noeppi.libx.config.ConfigManager.<clinit>(ConfigManager.java:154) ~[libx:1.16.3-1.0.64] {re:classloading}
	at mythicbotany.MythicBotany$.init(MythicBotany$.java:1) ~[mythicbotany:1.16.4-1.3.10] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at io.github.noeppi_noeppi.libx.mod.ModX.callGeneratedCode(ModX.java:98) ~[libx:1.16.3-1.0.64] {re:classloading}
	at io.github.noeppi_noeppi.libx.mod.registration.ModXRegistration.<init>(ModXRegistration.java:68) ~[libx:1.16.3-1.0.64] {re:classloading}
	at mythicbotany.MythicBotany.<init>(MythicBotany.java:46) ~[mythicbotany:1.16.4-1.3.10] {re:classloading}
```

**Comment by Apocalyptica20** [comment]
thanks

**Comment by landretk** [comment]
I think maybe this line needs to have Locale.ENGLISH specified for toLowerCase()

https://github.com/noeppi-noeppi/LibX/blob/1.16.3/src/main/java/io/github/noeppi_noeppi/libx/config/ConfigManager.java#L154

**Comment by landretk** [comment]
For anyone encountering this issue, a workaround is to add `-Duser.language=en -Duser.country=US` to your java arguments
